municipales_homepage:
    path:     /
    defaults: { _controller: MunicipalesBundle:Default:index }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl

municipales_candidacy_step_conditions:
    path:     /condiciones-alta-candidatura
    defaults: { _controller: MunicipalesBundle:Candidacy:stepConditions }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
municipales_candidacy_step1:
    path:     /alta-candidatura
    defaults: { _controller: MunicipalesBundle:Candidacy:step1 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
 
municipales_candidacy_step_verify:
    path:     /alta-candidatura-verificacion
    defaults: { _controller: MunicipalesBundle:Candidacy:stepVerify }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
municipales_candidacy_step2:
    path:     /alta-candidatura-paso-2
    defaults: { _controller: MunicipalesBundle:Candidacy:step2 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
municipales_candidacy_step3:
    path:     /alta-candidatura-paso3
    defaults: { _controller: MunicipalesBundle:Candidacy:step3 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
municipales_candidacy_step4:
    path:     /alta-candidatura-paso4
    defaults: { _controller: MunicipalesBundle:Candidacy:step4 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
municipales_candidacy_step5:
    path:     /alta-candidatura-paso5
    defaults: { _controller: MunicipalesBundle:Candidacy:step5 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
municipales_candidacy_step6:
    path:     /alta-candidatura-paso6
    defaults: { _controller: MunicipalesBundle:Candidacy:step6 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
municipales_candidacy_step7:
    path:     /alta-candidatura-paso7
    defaults: { _controller: MunicipalesBundle:Candidacy:step7 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl

municipales_candidacy_step8:
    path:     /alta-candidatura-paso8
    defaults: { _controller: MunicipalesBundle:Candidacy:step8 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl 

# http://municipales2015.listabierta.org/elmunicipioregistrado/resultados
town_results:
    path:     /{town}/resultados
    defaults: { _controller: MunicipalesBundle:Town:results }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
candidate_step1:
    path:     /{town}/altacandidaturas
    defaults: { _controller: MunicipalesBundle:Candidate:step1 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
              
town_candidacy_vote_step1:
    path:     /{town}/vota
    defaults: { _controller: MunicipalesBundle:Town:vote1 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
     
# http://municipales2015.listabierta.org./sms/inbound   
municipales_sms_inbound_callback:
    path:     /sms/inbound
    defaults: { _controller: MunicipalesBundle:SMSInbound:index }
    
# http://municipales2015.listabierta.org./sms/callback   
municipales_sms_callback:
    path:     /sms/callback
    defaults: { _controller: MunicipalesBundle:SMSInbound:callback }
