Listabierta\Bundle\MunicipalesBundle\Entity\AdminCandidacy:
    type: entity
    table: admin_candidacy
    repositoryClass: Listabierta\Bundle\MunicipalesBundle\Entity\AdminCandidacyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        dni:
            type: string
            length: '15'
        email:
            type: string
            length: 255
        province:
            type: string
            length: 255
        town:
            type: string
            length: 255
        phone:
            type: string
            length: '20'
        address:
            type: string
            length: '255'   
            nullable: TRUE
        todate:
            type: datetime
            nullable: TRUE
        fromdate:
            type: datetime
            nullable: TRUE
            
    lifecycleCallbacks: {  }
