Listabierta\Bundle\MunicipalesBundle\Entity\PhoneVerified:
    type: entity
    table: phone_verified
    repositoryClass: Listabierta\Bundle\MunicipalesBundle\Entity\PhoneVerifiedRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        phone:
            type: string
            length: 255
        email:
            type: string
            length: 255
        timestamp:
            type: integer
        mode:
            type: integer
            nullable: TRUE
            
    lifecycleCallbacks: {  }
